### ISSUE TITLE
Sending an email using SendGrid-PHP

### ISSUE THREAD

**Issue by skshiva** [phpearth/help#2]
I'm trying to send email using sendgrid-php web-api. I have no idea whats the error in the code or what to do to get a correct response status. I'm keep getting the response status as 0. Don't know why can anyone help me with this.

<?php 
require "vendor/autoload.php";
$apiKey = getenv('API_KEY');
$sg = new \SendGrid($apiKey);
if(isset($_POST['submit'])){
$full_name = $_POST['full_name'];
$mob_number = $_POST['mob_number'];
$email = $_POST['email'];
$message = $_POST['message']; 
$from = new SendGrid\Email("Admin", "skshiva90@gmail.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("End User", "skandaent2304@gmail.com");
$content = new SendGrid\Content(
"text/html",
"<h1>Sending with SendGrid is Fun and easy to do anywhere, even with PHP</h1><br>
Full Name: {$full_name}<br>
Mobile Number: {$mob_number}<br>
Email: {$email}<br>
Message: {$message}" 
);
$mail = new SendGrid\Mail($from, $subject, $to, $content); 
$response = $sg->client->mail()->send()->post($mail);
if ($response->statusCode() == 202) {
echo 'done';
} else {
echo 'false';
}
} else {
var_dump(
$response->statusCode(),
$response->headers(),
$response->body()
);
}
?>

**Comment by petk** [comment]
Seems like you're using somthing else than the Sendgrid's PHP SDK in above code. Instead use this SDK:
https://github.com/sendgrid/sendgrid-php

1.) Install it with Composer
2.) and use the example from the README here:
https://github.com/sendgrid/sendgrid-php#readme

**Comment by petk** [comment]
@skshiva In case you have more questions, just ask. Thanks.
